models:
  - name: psg_monthly_sales_make
    description: "Modelo intermedio que agrupa las ventas de manera mensual por vendedor y marca de coche"
    columns:
      - name: DDATE
        description: "Solo se encuentran fechas de inicio de cada mes"